version: '3.4'
services:
  course-backend:
    build:
      context: ./src/
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: wikitolearn/courses-backend
    ports:
    - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      MONGO_HOST: ${MONGO_HOST}
