version: '3.4'
services:
  course-backend:
    build:
      context: ./src/
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: "${DOCKER_REGISTRY}wikitolearn/courses-backend:${DOCKER_IMAGE_COURSES_BACKEND_TAG}"
    ports:
    - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      MONGO_HOST: ${MONGO_HOST}
